

WITH CTE_Afspraak_ns AS(
SELECT DISTINCT 
 AFS.PATIENTNR
,PP.MERGED
,PP.IsTestPatient
,PP.GESLACHT
,PP.POSTCODE
,PP.WOONPLAATS
,DATEDIFF(YEAR, PP.GEBDAT , RPP.STARTDATEPLAN) AS LEEFTIJD
,CAST(CAST(RPP.ENDTIMEPLAN AS DATETIME) - CAST(RPP.STARTTIMEPLAN AS DATETIME) AS TIME) AS TIMEDIFF
,AFS.INVOERDAT
,RPP.STARTDATEPLAN
,RPP.STARTTIMEPLAN
,AFS.AANKOMST
,AFS.AGENDA
,SA.[SUBAGENDA]
,SA.SPECCODE
,SA.TARAFD
,AFS.LOCATIONID
,loc.[DESCRIPTION]
,CASE WHEN AFS.[VOLDAAN] = 'J' THEN 'Ja' ELSE 'Nee' END AS [IsVoldaan]
,CASE WHEN COALESCE(RPP.STARTDATEPLAN, AFS.DATUM, '19000101') >= getdate() THEN 1
      WHEN ISNULL(NULLIF(AFS.[VOLDAAN],''),'') = '' THEN 2
      WHEN AFS.[VOLDAAN] = 'J' AND NULLIF(AFS.[AUTODAT],'') IS NULL THEN 3
      WHEN AFS.[VOLDAAN] = 'N' AND NULLIF(AFS.[AUTODAT],'') IS NULL THEN 4
      WHEN AFS.[VOLDAAN] = 'J' AND NOT NULLIF(AFS.[AUTODAT],'') IS NULL THEN 5
      WHEN AFS.[VOLDAAN] = 'N' AND NOT NULLIF(AFS.[AUTODAT],'') IS NULL THEN 6

      WHEN AFS.[VOLDAAN] = 'J' AND NOT NULLIF(AFS.[AUTODAT],'') IS NULL AND NULLIF(SAP.[AUTODAT],'') IS NOT NULL THEN 7
      WHEN AFS.[VOLDAAN] = 'N' AND NOT NULLIF(AFS.[AUTODAT],'') IS NULL AND NULLIF(SAP.[AUTODAT],'') IS NOT NULL THEN 8
      ELSE -1
  END as AfspraakstatusKey
,REDEN = MR.OMSCHR
,AC.CONSTYPE
,AFS.[CODE]
,AFS.MEMO
,AFS.OMSCHR


FROM  [sql2019hix-h02].[HiX_OVZ].[dbo].[AGENDA_AFSPRAAK] AS AFS
-- ophalen locatie (hengelo/almelo0
LEFT JOIN  [sql2019hix-h02].[HiX_OVZ].[dbo].CSZISLIB_LOCATION as loc on loc.LOCATIONID = AFS.LOCATIONID
LEFT JOIN [sql2019hix-h02].[HiX_OVZ].[dbo].[RP_PLANOBJECT] AS RPP ON afs.AFSPRAAKNR = RPP.LINKEDOBJECTID   AND RPP.LINKEDOBJECTCLASSID = 'AGENDA_AFSPRAAK'     
LEFT JOIN [sql2019hix-h02].[HiX_OVZ].[dbo].[AGENDA_SUBAGEND] AS SA  ON AFS.[AGENDA] = SA.[AGENDA]   AND AFS.[SUBAGENDA] = SA.[SUBAGENDA]               
LEFT JOIN [sql2019hix-h02].[HiX_OVZ].[dbo].[AGENDA_SUBAGENPROD] SAP ON SAP.SUBAGENDA = SA.SUBAGENDA
LEFT JOIN [sql2019hix-h02].[HiX_OVZ].[dbo].[AGENDA_AFSPCODE] AC ON AC.[CODE] = AFS.[CODE] AND AC.AGENDA = AFS.AGENDA
LEFT JOIN [sql2019hix-h02].[HiX_OVZ].[dbo].[PATIENT_PATIENT] PP ON PP.PATIENTNR = AFS.PATIENTNR
LEFT JOIN AGENDA_MUTATIEREDEN MR ON AFS.VERPLREDEN = MR.Code

-- Hieronder vul je de juiste agendacode in, en voor bijvoorbeeld functieafdelingen en radiologie moet je de SA.FAKTUREREN = 1 uitzetten
WHERE 1 = 1  
AND RPP.STARTDATEPLAN >= '2017-01-01'
AND RPP.STARTDATEPLAN < '2024-05-01'
AND AFS.PATIENTNR NOT LIKE '' AND SA.FAKTUREREN = 1  
AND AC.CONSTYPE IN ('E', 'H', 'V', '*')
)
 
-- Als je alle afspraken wil moet je de afspraakstatuskey uitcommenten
SELECT DISTINCT 
*, 
DUUR = (DATEPART(HOUR, TIMEDIFF) * 60) + (DATEPART(MINUTE, TIMEDIFF)) 
FROM CTE_Afspraak_ns 
WHERE IsTestPatient != 1 
ORDER BY STARTDATEPLAN

